name: Descomprimir
on: [workflow_dispatch]
jobs:
  unzip:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - run: |
          ls -la
          for z in *.zip; do unzip -o "$z" -d .; done
          rm -f *.zip
      - run: |
          git config user.name "fabrica"
          git config user.email "fabrica@bot.com"
          git add .
          git commit -m "Descomprimido auto" || true
          git push
